services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=phonolog'
      - 'POSTGRES_PASSWORD=secret123'
      - 'POSTGRES_USER=phonolog'
    ports:
      - '5432:5432'
    expose:
      - 5432
